# Generated by Django 4.2.23 on 2026-09-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='project_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['featured', '-created_at'], name='project_featured_created_idx'),
        ),
    ]
