# Generated by Django 4.2.23 on 2026-09-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_name', models.CharField(default='IANO / systems portfolio', max_length=120)),
                ('role', models.CharField(default='Python engineer, ML builder, systems thinker', max_length=180)),
                ('hero_text', models.TextField(default='I turn hard technical problems into calm, useful software.')),
                ('about_text', models.TextField(default='I build reliable products at the intersection of Python, machine learning, and thoughtful systems design.')),
                ('location', models.CharField(default='Nairobi, Kenya', max_length=120)),
                ('email', models.EmailField(default='hello@example.com', max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
