# Generated by Django 4.2.23 on 2026-09-14 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSourceContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=180)),
                ('role', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('contributed_on', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_source_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-contributed_on', '-created_at'),
            },
        ),
    ]
