# Generated by Django 4.2.23 on 2026-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='badge_alt',
            field=models.CharField(blank=True, help_text='Accessible description for the badge image.', max_length=180),
        ),
        migrations.AddField(
            model_name='certification',
            name='badge_image_url',
            field=models.URLField(blank=True, help_text='Direct HTTPS image URL for the badge artwork. Optional; a safe fallback is shown when unavailable.'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, help_text='Public verification page, such as a Credly public_url.'),
        ),
    ]
